project:
  type: website
  output-dir: docs 

website:
  title: "Analysis of Australian Road Deaths (ARDD Dataset, 1989–2021)"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Main EDA"
        href: notebooks/0-eda-australian-road-fatalities.qmd
      - text: "Motorcyclists"
        href: notebooks/2-motorcyclists.qmd
      - text: "Children"
        href: notebooks/1-vulnerable-road-users.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-location: right
    code-fold: true
