project:
  type: website

website:
  title: "Analysis of Australian Road Deaths (ARDD Dataset, 1989–2025)"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Main EDA"
        href: notebooks/0-eda-australian-road-fatalities.qmd
      - text: "Motorcyclists"
        href: notebooks/2-motorcyclists.qmd
      - text: "Children"
        href: notebooks/1-children.qmd

format:
  html:
    theme:
      light: [cosmo, assets/styles.css]
      dark: [darkly, assets/styles-dark.css]
    toc: true
    toc-location: right
    code-fold: true
    out-width: "100%"
